-- Risk 2 Fix: Add generation_source column to distinguish real vs mock content
-- Risk 3 Fix: Add better rewrite tracking columns

-- Create enum for generation source
CREATE TYPE generation_source_type AS ENUM ('ai', 'mock', 'video_transcript');

-- Add generation_source column to content_outputs
ALTER TABLE public.content_outputs
ADD COLUMN generation_source generation_source_type NOT NULL DEFAULT 'ai';

-- Add index for analytics queries
CREATE INDEX idx_content_outputs_generation_source ON public.content_outputs(generation_source);

-- Add rewrite tracking columns (already has rewrite_count, adding max limit reference)
ALTER TABLE public.content_outputs
ADD COLUMN rewrite_limit integer,
ADD COLUMN last_rewritten_at timestamp with time zone;

-- Add index for rewrite queries
CREATE INDEX idx_content_outputs_rewrite_tracking ON public.content_outputs(generation_id, rewrite_count);

COMMENT ON COLUMN public.content_outputs.generation_source IS 'Tracks whether content was generated by AI, mock data, or video transcript';
COMMENT ON COLUMN public.content_outputs.rewrite_limit IS 'Plan-based limit for rewrites of this content (copied from user plan at generation time)';
COMMENT ON COLUMN public.content_outputs.last_rewritten_at IS 'Timestamp of most recent rewrite operation';
