// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://udcttaicmvcpyoeixgrl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVkY3R0YWljbXZjcHlvZWl4Z3JsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAwNDg0MzMsImV4cCI6MjA4NTYyNDQzM30.K4_lDL3vwy4Rfz36Odw7B5xVEpXLcirGE_VfvIPobQ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});